#!/bin/bash

export LC_ALL=C

args=$(/usr/bin/getopt ejHV $*)
if [ $? != 0 ]; then
    echo Usage: $(basename $0) [-ejHV] [spot code, ...]
    echo
    echo "-e     show in English"
    echo "-j     show in Japanese (default)"
    echo "-H     show in horizontal"
    echo "-V     show in vertical   (default)"
    echo
    echo spot code
    echo
    echo open http://www.jma.go.jp/jp/amedas/ and select city or town name.
    echo
    echo URI http://www.jma.go.jp/jp/amedas_h/today-XXXXX.html
    echo
    echo "XXXXX is spot code. default is 44132. (Tokyo)"
    echo
    exit 2
fi

set -- $args

lng=jp
dir=v
for o in $args; do
    case "$o" in
	-e)
	    lng=en
	    shift;;
	-j)
	    lng=jp
	    shift;;
        -H)
	    dir=h
            shift;;
        -V)
	    dir=v
            shift;;
        --)
            shift; break;;
    esac
done

function get {
    /usr/bin/curl -s $1 | /usr/bin/awk -v lng=$lng '
    function trim(s) {
	gsub(/<[^>]+>/, "_", s);
	gsub(/__/, " ", s);
	gsub("_", "", s);
	gsub(/^[ \t]+/, "", s);
	return s
    }
    /class="td_title height2"/{
	if (lng == "jp") {
	    split(trim($0), ltmp, "　")
	    sub(/\(.*\)/, "", ltmp[2])
	    location = ltmp[2]
	} else {
	    sub(/^.*;/, "")
	    location =  trim($0)
	}
    }
    /class="block top bgcolor/{
	split(trim($0), label, " ")
    }
    /class="block middle bgcolor"/{
	if (lng == "en") {
	    sub("In 16", "")
	    sub("&deg;C", "℃")
	}
	split(trim($0), unit, " ")
    }
    /class="block middle">[0-9\.-]+/{
	t++;
	split(trim($0), value, " ")
    }
    END {
	if (t) {
	    print location, t":"
	    cut = (lng == "jp") ? 6 : 4

	    for (i = 1; i <= length(label); i++) {
		if (i == 3)	unit[i]=""
		if (value[i] ~ /nbsp/) continue
		print substr(label[i], 0, cut), value[i]unit[i]
	    }
	}
    }
'
}

function show {
    if [ $dir = "v" ]; then
	get $1
	echo
    elif [ $dir = "h" ]; then
	echo $(get $1)
    fi
}

deflist=${AMEDAS-44132}	# Tokyo
list=${*-$deflist}

for code in $list; do
	show http://www.jma.go.jp/$lng/amedas_h/today-${code}.html
done
